"use client";

export const documentation = [
  { id: "overview", title: "How the platform works", paragraphs: ["Stock Options Lab is a testnet proof of concept for fully collateralized calls and puts. Writers post individual offers with fixed terms; buyers purchase an entire lot. There is no AMM, price oracle, automatic settlement, partial exercise or resale in this interface.", "A call gives its buyer the right to buy the agreed Stock Token lot for the fixed exercise payment. A put gives its buyer the right to sell that lot for the fixed payment. The writer takes the other side if the buyer exercises."] },
  { id: "buying", title: "Buying an option", paragraphs: ["Choose a market, expiration and strike, then select an offer. Premium per token helps compare different lot sizes. Total premium is the payment for the entire option, not the exercise payment.", "Review the lot, exact total premium, exercise terms and deadline. Acknowledge manual exercise, approve the required premium when needed, then confirm the purchase. Buying delivers an exercise right, not the underlying tokens. Gas is separate. The premium is not refunded if the right goes unused."] },
  { id: "writing", title: "Writing and collateral", paragraphs: ["Choose Write Options, enter quantity, strike per token, premium per token and expiration, then review the totals. A covered call deposits the complete Stock Token lot; a cash-secured put deposits the complete exercise payment in the quote token.", "Writing creates a separate option contract that holds the collateral. An approval only authorizes spending; collateral moves only when the creation transaction confirms. Premium arrives only when someone buys. A purchased option cannot be canceled by its writer."] },
  { id: "manual-exercise", title: "Manual American exercise", paragraphs: ["The buyer must manually exercise a purchased option before its onchain expiration. American exercise means it can be exercised at any time after purchase and before that deadline, not only on the expiration date.", "For a call, the buyer delivers the full quote-token exercise payment and receives the full Stock Token lot. For a put, the buyer delivers the full Stock Token lot and receives the quote-token exercise payment. These are physical token transfers, not cash settlement based on a market price.", "Keep the required tokens, allowance and gas available. Buying a call spends the same quote-token balance you will later need to exercise. Submit early enough for the transaction to execute before the blockchain deadline: a pending transaction does not reserve the right. Countdown and calendar reminders are aids, not guarantees or automatic exercise."] },
  { id: "expiration", title: "Expiration, cancellation and recovery", paragraphs: ["There is no automatic exercise, payout or premium refund. At or after expiration the buyer can no longer exercise; the writer must reclaim unused collateral manually. The writer retains any premium already paid.", "Before expiration, a writer may cancel an unsold offer and recover its collateral. After expiration, the writer may reclaim collateral from an unsold or purchased, unexercised option. Exercised, canceled and reclaimed contracts are closed. Expired collateral remains in open positions until recovery confirms."] },
  { id: "prices", title: "Prices, token quantities and approvals", paragraphs: ["Strike per token equals total exercise payment divided by the underlying token quantity. Premium per token equals total premium divided by that quantity. These comparison values may be rounded: ≈ identifies approximations. Transactions use the exact agreed totals, never the rounded display.", "Quantities refer to token units, not a guaranteed number of shares. A Stock Token is not direct share ownership. No market price, fair value, portfolio valuation or profitability estimate is supplied here.", "Approvals authorize the required token amount to the intended spender. Confirm spender, network and amount in your wallet. An approval is not a purchase, exercise or collateral deposit. Rejected signatures do not complete an operation; a pending or reverted operation is not success."] },
  { id: "portfolio", title: "Portfolio and activity", paragraphs: ["Stock Tokens and stablecoins are shown separately. Available is the wallet balance; open orders and active collateral are held in option contracts. Reclaimable is expired collateral awaiting manual recovery. Total tracked includes these amounts and is not net portfolio value because collateral backs obligations.", "Positions are reconstructed from the configured onchain markets for your wallet, including activity from other devices. Expand a row to review its terms and available actions. Activity tracks transaction submissions locally in this browser; it is not a complete blockchain transaction history. Unknown balances show a dash, not zero."] },
  { id: "markets", title: "Curated markets and testnet limits", paragraphs: ["The website owner selects the markets shown here. Listing an asset does not deploy a factory or enable trading: each market needs a valid configured deployment for its token pair. Assets outside this catalog are not discoverable or tradable through this frontend.", "Everything here is testnet-only and has no real value. The Robinhood Chain Testnet frontend currently has no configured factory and is not a funded contract demo. Local Anvil transactions and synthetic-balance RPC forks are separate kinds of development evidence, not public deployments, audits or human validation."] },
];

export default function Docs({ onBack }: { onBack: () => void }) {
  return <div className="docs-layout"><nav className="docs-toc" aria-label="Documentation topics"><h2>On this page</h2>{documentation.map(section => <a key={section.id} href={`#${section.id}`}>{section.title}</a>)}<button className="text-button" onClick={onBack}>← Back to workspace</button></nav>
    <article className="docs-content"><p className="docs-intro">Understand each step before signing. This guide explains the product mechanics, not whether an option is a good trade.</p>{documentation.map(section => <section key={section.id} aria-labelledby={section.id}><h2 id={section.id} tabIndex={-1}>{section.title}</h2>{section.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</section>)}</article>
  </div>;
}
