"use client";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";

export const documentation = [
  { id: "overview", title: "How the platform works", paragraphs: ["Stock Options Lab is a development proof of concept targeting Robinhood Chain Testnet, with no public protocol deployment for fully collateralized calls and puts. Writers post individual offers with fixed terms; buyers purchase an entire lot. There is no AMM, price oracle, automatic settlement, or partial exercise. Version 2 and 3 markets also support whole-option resale; legacy contracts do not.", "A call gives its buyer the right to buy the agreed Stock Token lot for the fixed exercise payment. A put gives its buyer the right to sell that lot for the fixed payment. The writer takes the other side if the buyer exercises."] },
  { id: "buying", title: "Buying an option", paragraphs: ["Choose a market, expiration and strike, then select an offer. Expand a strike to compare the available token quantities. Each row is a separate, indivisible option. Option price is what you pay now for the entire right, not the exercise payment. New and resale listings appear together.", "Review the lot, exact total premium, exercise terms and deadline. Acknowledge manual exercise, approve the required premium when needed, then confirm the purchase. Buying delivers an exercise right, not the underlying tokens. Gas is separate. The premium is not refunded if the right goes unused."] },
  { id: "writing", title: "Writing and collateral", paragraphs: ["Choose Write Options, enter a quantity in multiples of 0.1 token, total exercise payment, total option price and expiration. All amounts are independent: changing quantity never silently changes either payment. A covered call deposits the complete Stock Token lot; a cash-secured put deposits the complete exercise payment in the quote token.", "Writing creates a separate option contract that holds the collateral. An approval only authorizes spending; collateral moves only when the creation transaction confirms. Premium arrives only when someone buys. A purchased option cannot be canceled by its writer."] },
  { id: "requests", title: "Requesting an option", paragraphs: ["In a version 3 market, choose Buy Requests to ask for a call or put. Enter a quantity in multiples of 0.1 token, total exercise payment, total premium and expiration. Set a separate acceptance deadline earlier than expiration. You reserve only the premium in the factory; you do not own an option yet.", "A writer accepts the complete quantity and deposits all collateral. The factory creates one independent option for you and pays your reserved premium to the writer in the same transaction. Ten tokens can be 100 lots in one option contract. No partial fills or automatic matching are supported.", "Until acceptance, only the requester can cancel to recover the entire premium. After the acceptance deadline, the premium still needs a refund transaction. After acceptance, manage the option in Portfolio; its paid premium is not refundable. Exercise requires the full payment or tokens before expiration."] },
  { id: "resale", title: "Reselling your option", paragraphs: ["In a version 2 or 3 market, expand a purchased position and enter a total resale price. The current holder may list, update or remove their listing before expiration. Buying a resale pays that price to the current holder and transfers the entire exercise right atomically. The writer, collateral, token quantity, exercise payment and deadline stay unchanged.", "A listing does not lock the right: its holder can still exercise before someone buys. Purchases verify the reviewed seller, price and listing nonce; changed or withdrawn quotes fail instead of charging a different price. The previous holder loses exercise permission when the sale confirms. Self-purchases and original-writer buybacks are not supported.", "Reselling is not writing a new option: no second collateral deposit or new contract is created. There are no platform fees, partial sales, free transfers or guaranteed liquidity. Legacy version 1 options cannot be resold and are not migrated."] },
  { id: "manual-exercise", title: "Manual American exercise", paragraphs: ["The buyer must manually exercise a purchased option before its onchain expiration. American exercise means it can be exercised at any time after purchase and before that deadline, not only on the expiration date.", "For a call, the buyer delivers the full quote-token exercise payment and receives the full Stock Token lot. For a put, the buyer delivers the full Stock Token lot and receives the quote-token exercise payment. These are physical token transfers, not cash settlement based on a market price.", "Keep the required tokens, allowance and gas available. Buying a call spends the same quote-token balance you will later need to exercise. Submit early enough for the transaction to execute before the blockchain deadline: a pending transaction does not reserve the right. Countdown and calendar reminders are aids, not guarantees or automatic exercise."] },
  { id: "expiration", title: "Expiration, cancellation and recovery", paragraphs: ["There is no automatic exercise, payout or premium refund. At or after expiration the buyer can no longer exercise; the writer must reclaim unused collateral manually. The writer retains any premium already paid.", "Before expiration, a writer may cancel an unsold offer and recover its collateral. After expiration, the writer may reclaim collateral from an unsold or purchased, unexercised option. Exercised, canceled and reclaimed contracts are closed. Expired collateral remains in open positions until recovery confirms."] },
  { id: "prices", title: "Prices, token quantities and approvals", paragraphs: ["Strike per token equals total exercise payment divided by the underlying token quantity. It is used only to group offers, not as the amount you pay. The strike reference may be rounded: ≈ identifies approximations. Transactions use the exact agreed totals, never the rounded display.", "Quantities refer to token units, not a guaranteed number of shares. A Stock Token is not direct share ownership. The five named local mock markets use rounded September 9, 2026 reference prices and synthetic premiums for UI testing, not a live feed, fair value, portfolio valuation or profitability estimate.", "Approvals authorize the required token amount to the intended spender. Confirm spender, network and amount in your wallet. An approval is not a purchase, exercise or collateral deposit. Rejected signatures do not complete an operation; a pending or reverted operation is not success."] },
  { id: "portfolio", title: "Portfolio and activity", paragraphs: ["Stock Tokens and stablecoins are shown separately. Available is the wallet balance; open orders and active collateral are held in option contracts. Reclaimable is expired collateral awaiting manual recovery. Request premiums are separately reserved in the factory; refundable premiums belong to unaccepted requests whose acceptance deadline passed. Both require a cancellation transaction to return to the wallet. Total tracked includes these amounts and is not net portfolio value because collateral backs obligations.", "Positions are reconstructed from the configured onchain markets for your wallet, including past holders through version 2 purchase and resale events. Payments show what your wallet actually paid or received; resale proceeds go to the selling holder, not the original writer. Expand a row to review its terms and available actions. Activity tracks transaction submissions locally in this browser; it is not a complete blockchain transaction history. Unknown balances show a dash, not zero."] },
  { id: "markets", title: "Curated markets and testnet limits", paragraphs: ["The website owner selects the markets shown here. Listing an asset does not deploy a factory or enable trading: each market needs a valid configured deployment for its token pair. Assets outside this catalog are not discoverable or tradable through this frontend.", "Local mock tokens have no real value. Robinhood testnet deployment and public acceptance testing remain pending. The Robinhood Chain Testnet frontend currently has no configured factory and is not a funded contract demo. Local Anvil transactions and synthetic-balance RPC forks are separate kinds of development evidence, not public deployments, audits or human validation."] },
];

export default function Docs({ onBack }: { onBack: () => void }) {
  return <div className="docs-layout"><nav className="docs-toc" aria-label="Documentation topics"><h2>On this page</h2>{documentation.map(section => <a key={section.id} href={`#${section.id}`}>{section.title}</a>)}<button className="text-button" onClick={onBack}>← Back to workspace</button></nav>
    <article className="docs-content"><div className="docs-hero"><span className="eyebrow">PLATFORM GUIDE</span><h2>A right today. A decision before expiration.</h2><p>Buy, write or request → Hold or resell → Exercise before the deadline</p></div><p className="docs-intro">Understand each step before signing. This guide explains the product mechanics, not whether an option is a good trade.</p><div className="docs-comparison"><Table><TableHeader><TableRow><TableHead>Buyer’s right</TableHead><TableHead>Deliver at exercise</TableHead><TableHead>Receive at exercise</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>Call · Buy tokens</TableCell><TableCell>Agreed total payment</TableCell><TableCell>Agreed token quantity</TableCell></TableRow><TableRow><TableCell>Put · Sell tokens</TableCell><TableCell>Agreed token quantity</TableCell><TableCell>Agreed total payment</TableCell></TableRow></TableBody></Table></div>{documentation.map(section => <section key={section.id} aria-labelledby={section.id}><h2 id={section.id} tabIndex={-1}>{section.title}</h2>{section.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</section>)}</article>
  </div>;
}
