import { mkdir, writeFile } from 'node:fs/promises';
import { artifact, atRoot } from './config.mjs';
const exports = [ ['optionFactoryAbi', 'OptionFactory'], ['optionAbi', 'Option'], ['erc20Abi', 'MockUSD'] ];
let source = '// Generated by npm run abi from the compiled contracts. Do not edit.\n';
for (const [name, contract] of exports) {
  const { abi } = await artifact(contract);
  source += `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
source += `export const faucetAbi = ${JSON.stringify((await artifact('MockUSD')).abi.filter(x => x.type === 'function' && x.name === 'faucet'), null, 2)} as const;\n`;
await mkdir(atRoot('web/lib/generated'), { recursive: true });
await writeFile(atRoot('web/lib/generated/abis.ts'), source);
console.log('Generated frontend ABIs from Solidity artifacts.');
