// Executed on an isolated Anvil instance; no account-zero transactions or public network access.
import assert from 'node:assert/strict';
import { createPublicClient, createWalletClient, decodeEventLog, encodeFunctionData, erc20Abi, http } from 'viem';
import { getMarkets, getPortfolio, prepareCreateOffer, prepareBuy, prepareBuyResale, prepareListResale, prepareCancelResale, prepareExercise, optionAbi, optionFactoryAbi } from '@stock-options-lab/sdk';
import { network, readJson, saveJson, mined } from './config.mjs';
import { assertLocalDemo } from './demo-config.mjs';
import { executeOperation, marketFromManifest } from './sdk-operation.mjs';

const chain = network('local'), url = chain.rpcUrls.default.http[0];
const client = createPublicClient({ chain, transport: http(url, { batch: { batchSize: 64, wait: 1 } }), cacheTime: 0, pollingInterval: 25 });
const accounts = await client.request({ method: 'eth_accounts' });
assertLocalDemo(url, await client.getChainId(), await client.request({ method: 'web3_clientVersion' }), accounts);
const manifest = await readJson(process.env.DEMO_MANIFEST ?? 'deployments/31337.json');
const record = [manifest, ...(manifest.markets ?? [])].find(m => (m.version ?? 1) >= 2);
assert(record, 'Deploy a V2 or V3 local market before resale integration checks.');
const market = marketFromManifest({ ...manifest, ...record });
const actor = index => ({ publicClient: client, account: { address: accounts[index], type: 'json-rpc' }, walletClient: createWalletClient({ chain, account: accounts[index], transport: http(url) }) });
const writer = actor(3), buyer = actor(8), next = actor(9);
const receipts = [];
const run = async (who, operation) => { const receipt = await executeOperation(who, await operation); receipts.push({ action: (await operation).action, hash: receipt.transactionHash, block: receipt.blockNumber }); return receipt; };
const read = (address, functionName) => client.readContract({ address, abi: optionAbi, functionName });
const faucetAbi = [{ type: 'function', name: 'faucet', stateMutability: 'nonpayable', inputs: [], outputs: [] }];
for (const who of [writer, buyer, next]) for (const token of [market.underlying, market.quote]) await mined(client, await who.walletClient.writeContract({ address: token.address, abi: faucetAbi, functionName: 'faucet' }));
const balances = async option => Promise.all([writer.account.address, buyer.account.address, next.account.address, option, market.factory].map(async account => Promise.all([market.underlying, market.quote].map(token => client.readContract({ address: token.address, abi: erc20Abi, functionName: 'balanceOf', args: [account] })))));
for (const optionType of [0, 1]) {
  const terms = { optionType, quantity: 5n * 10n ** 17n, strikeTotal: 185_000000n, premium: 8_000000n, expiry: (await client.getBlock()).timestamp + 86400n };
  const receipt = await run(writer, prepareCreateOffer(client, market, writer.account.address, terms));
  const event = receipt.logs.flatMap(log => { try { return [decodeEventLog({ abi: optionFactoryAbi, ...log })]; } catch { return []; } }).find(log => log.eventName === 'OptionCreated');
  const option = event.args.option;
  await run(buyer, prepareBuy(client, market, buyer.account.address, option));
  await run(buyer, prepareListResale(client, market, buyer.account.address, option, 10_000000n));
  const stale = await prepareBuyResale(client, market, next.account.address, option, { seller: buyer.account.address, price: 10_000000n, nonce: 1n });
  await run(buyer, prepareListResale(client, market, buyer.account.address, option, 11_000000n));
  const before = await balances(option);
  const rejected = await client.waitForTransactionReceipt({ hash: await next.walletClient.sendTransaction({ ...stale.request, gas: 500000n }) });
  assert.equal(rejected.status, 'reverted');
  assert.deepEqual(await balances(option), before);
  assert.equal((await read(option, 'buyer')).toLowerCase(), buyer.account.address.toLowerCase());
  assert.equal(await read(option, 'listingNonce'), 2n);
  await run(next, prepareBuyResale(client, market, next.account.address, option, { seller: buyer.account.address, price: 11_000000n, nonce: 2n }));
  const after = await balances(option);
  assert.deepEqual(after[0], before[0], 'Writer receives no resale income');
  assert.equal(after[1][1] - before[1][1], 11_000000n);
  assert.equal(after[2][1] - before[2][1], -11_000000n);
  assert.deepEqual(after[3], before[3], 'Collateral does not move on resale');
  await assert.rejects(() => prepareExercise(client, market, buyer.account.address, option));
  await run(next, prepareListResale(client, market, next.account.address, option, 12_000000n));
  await run(next, prepareCancelResale(client, market, next.account.address, option));
  await run(next, prepareListResale(client, market, next.account.address, option, 12_000000n));
  const snapshots = await getMarkets(client, [market]);
  const past = await getPortfolio(client, [market], buyer.account.address, snapshots);
  const history = past.positions.find(p => p.address.toLowerCase() === option.toLowerCase());
  assert.equal(history.trades.length, 2, 'Past owner retains actual purchase and resale history');
  assert.equal(history.trades[1].price, 11_000000n);
  await run(next, prepareExercise(client, market, next.account.address, option));
  const terminal = await balances(option);
  for (let token = 0; token < 2; token++) assert.equal(terminal.reduce((sum, b) => sum + b[token], 0n), before.reduce((sum, b) => sum + b[token], 0n));
  assert.deepEqual(terminal[3], [0n, 0n]);
  assert.equal(await read(option, 'resalePrice'), 0n);
  assert.equal(await read(option, 'state'), 2);
  const unavailable = encodeFunctionData({ abi: optionAbi, functionName: 'buyResale', args: [next.account.address, 12_000000n, 6n] });
  await assert.rejects(() => client.call({ account: buyer.account.address, to: option, data: unavailable }));
  console.log(`PASS ${optionType === 0 ? 'call' : 'put'} resale: stale quote rollback, conservation, history, old-holder rejection, listed exercise`);
}
await saveJson('deployments/local-resale-smoke.json', { chainId: 31337, rpcUrl: url, factory: market.factory, source: 'Executed local Anvil transactions; not a public deployment or audit', receipts });
